[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
upload_port = COM3
monitor_port = COM3
monitor_speed = 115200
upload_speed = 921600

board_build.partitions = huge_app.csv

lib_deps =
    madhephaestus/ESP32Servo@^3.0.5
    tzapu/WiFiManager@^2.0.17
    mobizt/FirebaseClient@^1.4.13
    bblanchon/ArduinoJson@^7.2.1

build_flags =
    -DCORE_DEBUG_LEVEL=3
